In [18]:
import pandas as pd

df = pd.read_csv("../data/processed/employee_attrition_clean.csv")

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2

In [19]:
X = df.drop("Attrition", axis=1)

y = df["Attrition"]

In [20]:
y = y.map({
    "No": 0,
    "Yes": 1
})

In [21]:
y

0       1
1       0
2       1
3       0
4       0
       ..
1465    0
1466    0
1467    0
1468    0
1469    0
Name: Attrition, Length: 1470, dtype: int64

In [22]:
categorical_cols = X.select_dtypes(include="object").columns.tolist()
numerical_cols = X.select_dtypes(include=["int64", "float64"]).columns.tolist()

print("Categorical:", categorical_cols)
print("Numerical:", numerical_cols)

Categorical: ['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime']
Numerical: ['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

C:\Users\shara\AppData\Local\Temp\ipykernel_25916\3515062951.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include="object").columns.tolist()

In [23]:
for col in categorical_cols:
    print(f"{col}: {X[col].nunique()} unique values")

BusinessTravel: 3 unique values
Department: 3 unique values
EducationField: 6 unique values
Gender: 2 unique values
JobRole: 9 unique values
MaritalStatus: 3 unique values
OverTime: 2 unique values

In [24]:
X_vif = pd.get_dummies(X, drop_first=True)

X_vif.head()
X_vif.dtypes
X_vif = X_vif.astype(float)

In [25]:
pip install statsmodels

Requirement already satisfied: statsmodels in d:\talnetguard_ai\.venv\lib\site-packages (0.14.6)
Requirement already satisfied: numpy<3,>=1.22.3 in d:\talnetguard_ai\.venv\lib\site-packages (from statsmodels) (2.4.6)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in d:\talnetguard_ai\.venv\lib\site-packages (from statsmodels) (1.18.0)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in d:\talnetguard_ai\.venv\lib\site-packages (from statsmodels) (3.0.3)
Requirement already satisfied: patsy>=0.5.6 in d:\talnetguard_ai\.venv\lib\site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in d:\talnetguard_ai\.venv\lib\site-packages (from statsmodels) (26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\talnetguard_ai\.venv\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\talnetguard_ai\.venv\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2026.3)
Requirement already satisfied: six>=1.5 in d:\talnetguard_ai\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()

vif["Feature"] = X_vif.columns

vif["VIF"] = [
    variance_inflation_factor(X_vif.values, i)
    for i in range(X_vif.shape[1])
]

vif.sort_values("VIF", ascending=False)

                              Feature         VIF
13                  PerformanceRating  159.387171
25  Department_Research & Development   93.827131
7                            JobLevel   62.227023
26                   Department_Sales   52.755404
9                       MonthlyIncome   52.694329
12                  PercentSalaryHike   44.880149
27       EducationField_Life Sciences   39.775969
0                                 Age   35.070092
29             EducationField_Medical   30.700183
39            JobRole_Sales Executive   18.071145
18                    WorkLifeBalance   16.232392
6                      JobInvolvement   15.632959
16                  TotalWorkingYears   15.309246
28           EducationField_Marketing   11.916631
5                          HourlyRate   11.570564
19                     YearsAtCompany   10.908259
3                           Education    9.657297
31    EducationField_Technical Degree    9.481708
24       BusinessTravel_Travel_Rarely    8.071989
14           RelationshipSatisfaction    7.428345
4             EnvironmentSatisfaction    7.271061
8                     JobSatisfaction    7.164283
22               YearsWithCurrManager    6.650587
20                 YearsInCurrentRole    6.591133
30               EducationField_Other    6.243015
17              TrainingTimesLastYear    5.869453
40       JobRole_Sales Representative    5.541868
1                           DailyRate    5.089007
10                        MonthlyRate    5.087519
33            JobRole_Human Resources    4.731525
35                    JobRole_Manager    4.483146
42               MaritalStatus_Single    4.381639
38         JobRole_Research Scientist    4.168363
34      JobRole_Laboratory Technician    3.785261
15                   StockOptionLevel    3.522762
41              MaritalStatus_Married    3.369509
23   BusinessTravel_Travel_Frequently    2.898769
37          JobRole_Research Director    2.825951
11                 NumCompaniesWorked    2.772156
32                        Gender_Male    2.559719
21            YearsSinceLastPromotion    2.502230
2                    DistanceFromHome    2.328946
36     JobRole_Manufacturing Director    2.122368
43                       OverTime_Yes    1.441912

In [27]:
for col in categorical_cols:
    print(f"{col}: {X[col].nunique()} unique values")

BusinessTravel: 3 unique values
Department: 3 unique values
EducationField: 6 unique values
Gender: 2 unique values
JobRole: 9 unique values
MaritalStatus: 3 unique values
OverTime: 2 unique values

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [29]:
X_train.to_csv("../data/processed/X_train.csv", index=False)
X_test.to_csv("../data/processed/X_test.csv", index=False)

y_train.to_csv("../data/processed/y_train.csv", index=False)
y_test.to_csv("../data/processed/y_test.csv", index=False)

In [30]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(1176, 30)
(294, 30)
(1176,)
(294,)

In [31]:
print(y_train.value_counts(normalize=True))

print(y_test.value_counts(normalize=True))

Attrition
0    0.838435
1    0.161565
Name: proportion, dtype: float64
Attrition
0    0.840136
1    0.159864
Name: proportion, dtype: float64